apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jaimo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.image-pull-policy: Never
    kompose.service.type: nodeport
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: api
  type: NodePort
status:
  loadBalancer: {}
