apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jaimo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jaimo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/11-kubernetes-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - image: mongo:7
          name: db
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
