apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\jaimo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.image-pull-policy: Never
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\jaimo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
        kompose.image-pull-policy: Never
        kompose.service.expose: "true"
        kompose.service.type: LoadBalancer
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/11-kubernetes-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: web
          imagePullPolicy: Never
          name: web
          ports:
            - containerPort: 80
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
