apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\jaimo\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -f docker-compose.yml
    kompose.image-pull-policy: Never
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web-tcp
  name: web-tcp
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 80
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  loadBalancer: {}
