services:
  db:
    image: mongo:7
  api:
    build: api
    ports: 
      - "8080:8080"
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  web:
    build: web
    ports: 
      - "8081:80"

